//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplyForm
    {
        public int Id { get; set; }
        public byte CVcontent { get; set; }
        public string CVname { get; set; }
        public string Coverletter { get; set; }
        public System.DateTime Timesent { get; set; }
        public string Status { get; set; }
        public int PostId { get; set; }
        public int JobSeekerId { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual JobSeeker JobSeeker { get; set; }
    }
}
