//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobApplication
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JobAppDFEntities : DbContext
    {
        public JobAppDFEntities()
            : base("name=JobAppDFEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Post> Posts { get; set; }
        public virtual DbSet<ApplyForm> ApplyForms { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<PostDescCatalog> PostDescCatalogs { get; set; }
        public virtual DbSet<PostImageCatalog> PostImageCatalogs { get; set; }
        public virtual DbSet<PostTagCatalog> PostTagCatalogs { get; set; }
    }
}
